
#
#░█████╗░░█████╗░██████╗░███████╗
#██╔══██╗██╔══██╗██╔══██╗██╔════╝
#██║░░╚═╝██║░░██║██║░░██║█████╗░░
#██║░░██╗██║░░██║██║░░██║██╔══╝░░
#╚█████╔╝╚█████╔╝██████╔╝███████╗
#░╚════╝░░╚════╝░╚═════╝░╚══════╝
#
#
#██████╗░██╗░░░██╗
#██╔══██╗╚██╗░██╔╝
#██████╦╝░╚████╔╝░
#██╔══██╗░░╚██╔╝░░
#██████╦╝░░░██║░░░
#╚═════╝░░░░╚═╝░░░
#
#
#
#░█████╗░██╗░░░░░██╗░█████╗░██╗░░██╗███████╗██████╗░████████╗██████╗░░█████╗░███╗░░██╗
#██╔══██╗██║░░░░░██║██╔══██╗██║░██╔╝██╔════╝██╔══██╗╚══██╔══╝██╔══██╗██╔══██╗████╗░██║
#██║░░╚═╝██║░░░░░██║██║░░╚═╝█████═╝░█████╗░░██║░░██║░░░██║░░░██████╔╝███████║██╔██╗██║
#██║░░██╗██║░░░░░██║██║░░██╗██╔═██╗░██╔══╝░░██║░░██║░░░██║░░░██╔══██╗██╔══██║██║╚████║
#╚█████╔╝███████╗██║╚█████╔╝██║░╚██╗███████╗██████╔╝░░░██║░░░██║░░██║██║░░██║██║░╚███║
#░╚════╝░╚══════╝╚═╝░╚════╝░╚═╝░░╚═╝╚══════╝╚═════╝░░░░╚═╝░░░╚═╝░░╚═╝╚═╝░░╚═╝╚═╝░░╚══╝

menu:
  title: "§l§a•[ §bMenu §cRepair Item§a ]•"
  exit: "§l§a• §cExit§a •"
not-items-or-armor: "§l§cIn your hand is not §bTools or §bArmor"

money:
  title: "§l§a•[ §cRepair Item §bMoney§a ]•"
  button-not-enough: "§l§a• §cFix §bMoney§a •\n§bYou Don't Have Enough Money To Repair"
  button-enough: "§l§a• §cFix §bMoney§a •"
  confirm: "§l§a• §cConfirm §a•"
  no: "§l§a• §cNo §a•\n§bFor me back"
  percent: 1
  price: 1000
  successfully: "§l§aYou have repaired item §6{item_name} a for §b{price} money"
  fail: "§l§cYou do not have enough §6{price} §cmoney to fix this item!"
exp:
  title: "§l§a•[ §cRepair Item §bEXP§a ]•"
  button-not-enough: "§l§a• §cFix §bExp§a •\n§bYou Don't Have Enough Exp To Repair"
  button-enough: "§l§a• §cFix §bExp§a •"
  confirm: "§l§a• §cConfirm §a•"
  no: "§l§a• §cNo §a•\n§bFor me back"
  percent: 1
  price: 10
  successfully: "§l§aYou have repaired item §6{item_name} a for §b{price} exp"
  fail: "§l§cYou do not have enough §6{price} §cexp to fix this item!"

#NOTE
#Parcent is the amount or exp that you have to pay for each item's durability. Please set default to 1!!

#Price is the minimum amount a player needed to be able to use Fix Money or Fix Exp
#{price} = repair money
#{item_name} = item name
